name: CD

on:
  workflow_dispatch:
  push:
    branches:
    - master

env:
  REGISTRY_URL: "ghcr.io"
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    name: Build Container Images
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Build Dockerfile
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: "ghcr.io/nikeee/imagemagick-fpx:latest"
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.source="https://github.com/${{ github.repository }}
        cache-from: type=registry,ref=ghcr.io/nikeee/imagemagick-fpx:latest
